app:
  image: flashcards
  links:
    - postgres_database
  ports:
    - "80:9000"
  environment:
    - FC_PROFILE=qa
app:
  image: flashcards
  links:
    - postgres_database
  ports:
    - "9000:9000"
  environment:
    - FC_PROFILE=dev
postgres_database:
  restart: always
  image: sameersbn/postgresql:9.5-2
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false
    - DB_USER=fcuser
    - DB_PASS=password
    - DB_NAME=flash_cards