app_dev:
  image: flashcards
  links:
    - postgres_database
  ports:
    - "${FC_PORT}:9000"
  environment:
    - FC_PROFILE=${FC_PROFILE}
postgres_database:
  restart: always
  image: sameersbn/postgresql:9.5-2
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false
    - DB_USER=fcuser
    - DB_PASS=password
    - DB_NAME=flash_cards
